### ISSUE TITLE
can not change language

### ISSUE THREAD

**Issue by levinit** [pzorin/qgo#52]
no matter which language I chose,it shown in English.Why is that...thank you.

**Comment by pzorin** [comment]
Probably something got broken during the Qt5 port.
I haven't thought about translations then.

**Comment by pzorin** [comment]
I have changed the code so that the system locale is used. However, translations have not been updated after all the refactoring that I have done, so they are incomplete to the point of probably being useless. Binary translation files are not generated automatically by the current build process, so the existing partial translations will not be used unless you run lrelease and install them manually. Only the default Qt buttons will be translated in any case.
